# Generated by Django 4.2.1 on 2024-02-12 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTableM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('fromWhere', models.TextField()),
                ('toWhere', models.TextField()),
                ('platform', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('date', models.DateField()),
                ('bus_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.bustablem')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('ticket_status', models.BooleanField()),
                ('ticket_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip_race_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.bustrip')),
            ],
        ),
        migrations.CreateModel(
            name='SeatN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('bus_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.bustrip')),
            ],
        ),
        migrations.AddField(
            model_name='bustrip',
            name='freeSeats',
            field=models.ManyToManyField(blank=True, to='busCont.seatn'),
        ),
    ]
