# Generated by Django 4.2.1 on 2023-11-27 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTableM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('raceNum', models.IntegerField()),
                ('fromWhere', models.TextField()),
                ('toWhere', models.TextField()),
                ('seats', models.IntegerField()),
                ('freeSeats', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('bus_name_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.bustablem')),
                ('ticket_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('date', models.DateField()),
                ('bus_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.bustablem')),
            ],
        ),
    ]
