# Generated by Django 4.2.1 on 2023-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustablem',
            name='raceNum',
            field=models.IntegerField(),
        ),
    ]
