# Generated by Django 4.2.1 on 2023-11-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustablem',
            name='raceNum',
        ),
    ]
