# Generated by Django 4.2.1 on 2024-02-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustablem',
            name='seats',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
