# Generated by Django 4.2.1 on 2024-02-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustablem',
            name='tripkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='busCont.bustrip'),
            preserve_default=False,
        ),
    ]
