# Generated by Django 4.2.1 on 2023-11-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0002_remove_bustablem_racenum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bus_name_ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip_race_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='busCont.bustrip'),
            preserve_default=False,
        ),
    ]
