# Generated by Django 4.2.1 on 2024-02-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0002_bustablem_tripkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustablem',
            name='tripkey',
        ),
    ]
