# Generated by Django 4.2.1 on 2023-11-27 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('busCont', '0002_alter_bustablem_racenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustablem',
            name='bus_name',
            field=models.TextField(default=44, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('bus_name_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.bustablem')),
                ('ticket_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
