# Generated by Django 4.2.1 on 2024-02-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0002_remove_bustablem_seats_ticket_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatn',
            name='bus_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.ticket'),
        ),
    ]
