# Generated by Django 4.2.1 on 2024-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0003_alter_seatn_bus_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
