# Generated by Django 4.2.1 on 2023-11-28 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0003_remove_ticket_bus_name_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustablem',
            name='freeSeats',
        ),
        migrations.CreateModel(
            name='SeatN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.bustablem')),
            ],
        ),
    ]
