# Generated by Django 4.2.1 on 2023-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0004_remove_bustablem_freeseats_seatn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustablem',
            name='freeSeats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SeatN',
        ),
    ]
