# Generated by Django 4.2.1 on 2023-11-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busCont', '0005_bustablem_freeseats_delete_seatn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustablem',
            name='freeSeats',
        ),
        migrations.CreateModel(
            name='SeatN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('bus_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busCont.bustablem')),
            ],
        ),
        migrations.AddField(
            model_name='bustablem',
            name='freeSeats',
            field=models.ManyToManyField(blank=True, to='busCont.seatn'),
        ),
    ]
